name: Test

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github-actions
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: schani/quicktype
      env:
        CI: true
      options: --cpus 1
    strategy:
      matrix:
        fixture:
          - golang
          - rust
          - swift
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install
        run: |
          npm install --unsafe-perm
      - name: Test ${{ matrix.fixture }} fixture
        run: npm test
        env:
          FIXTURE: ${{ matrix.fixture }}
          CPUs: 1
