name: Test

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  test-golang:
    name: Test golang
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Test
        run: FIXTURE=golang npm test
  test-swift:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Install Swift
        run: |
          sudo apt-get install clang libcurl3 libpython2.7 libpython2.7-dev libcurl3 libcurl-openssl1.0-dev
          wget https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz
          tar xzf swift-4.2.1-RELEASE-ubuntu18.04.tar.gz
          sudo mv swift-4.2.1-RELEASE-ubuntu18.04 /usr/share/swift
      - run: |
          export PATH=/usr/share/swift/usr/bin:$PATH
          FIXTURE=swift npm test
  test-objective-c:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - run: |
          FIXTURE=objective-c npm test
