name: Test

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  test-golang:
    name: Test golang
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Test
        run: FIXTURE=golang npm test
  test-swift:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: |
          npm install
          apt-get install swift
      - uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - run: FIXTURE=swift npm test
