name: Test

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: functions
        run: npm install
      - name: Build
        working-directory: functions
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  test-golang:
    name: Test golang
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Download Build
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Test
        run: FIXTURE=golang npm test
