name: Test quicktype

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - github-actions
jobs:
  build:
    name: Build quicktype
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fixture:
          - golang
          - rust
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install
        run: |
          npm install --unsafe-perm
      - name: Test ${{ matrix.fixture }} fixture
        run: npm test
        env:
          FIXTURE: ${{ matrix.fixture }}
